# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch

import torch
# Create random tensor
random_tensor = torch.rand(7,7)
random_tensor

tensor([[0.7353, 0.6895, 0.8171, 0.7074, 0.3944, 0.6564, 0.3685],
        [0.1256, 0.3138, 0.4537, 0.5133, 0.3897, 0.0550, 0.0633],
        [0.3996, 0.9334, 0.9209, 0.5859, 0.0130, 0.3753, 0.8216],
        [0.0451, 0.5976, 0.6542, 0.2696, 0.7657, 0.5962, 0.9015],
        [0.6167, 0.7376, 0.7547, 0.6746, 0.7097, 0.0988, 0.6195],
        [0.6862, 0.0462, 0.2624, 0.8345, 0.3997, 0.7885, 0.0492],
        [0.8381, 0.8447, 0.8184, 0.0982, 0.7992, 0.9288, 0.6936]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [9]:
# Create another random tensor
second_random_tensor = torch.rand(1,7)
Second_Transposed = second_random_tensor.T
# Perform matrix multiplication
result_tensor = torch.matmul(random_tensor, Second_Transposed)
result_tensor

tensor([[2.3319],
        [0.9743],
        [1.9028],
        [1.4257],
        [2.0623],
        [1.7806],
        [2.4282]])

**bold text**### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [18]:
# Set manual seed
Seed = 0
# Create two random tensors
torch.manual_seed(0)
random_tensor1 = torch.rand(7,7)

torch.manual_seed(0)
sec_random_tensor = torch.rand(1,7)

print(random_tensor1)
print(sec_random_tensor)
print(random_tensor1 == sec_random_tensor)

sec_transposed = sec_random_tensor.T

# Matrix multiply tensors
matrix_result = torch.matmul(random_tensor1, sec_transposed)
print(matrix_result)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])
tensor([[ True,  True,  True,  True,  True,  True,  True],
        [False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False]])
tensor([[1.5985],
        [1.1173],
        [1.2741],
  

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [6]:
import torch
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device:  {device}")
# Create two random tensors on GPU
one = torch.rand(2,3).to(device)
two = torch.rand(2,3).to(device)
print(one)
print(two)


Device:  cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [10]:
# Perform matmul on tensor_A and tensor_B
one = torch.rand(2,3).to(device)
two = torch.rand(2,3).to(device)
transposed = two.T
result_matmul = torch.matmul(one, transposed)
print(result_matmul, result_matmul.shape)

tensor([[1.2142, 0.9098],
        [1.1797, 0.8655]], device='cuda:0') torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [13]:
# Find max
print(result_matmul.max())
# Find min
print(result_matmul.min())

tensor(1.2142, device='cuda:0')
tensor(0.8655, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [14]:
# Find arg max
print(result_matmul.argmax())

# Find arg min
print(result_matmul.argmin())

tensor(0, device='cuda:0')
tensor(3, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [18]:
# Set seed
torch.manual_seed(7)

# Create random tensor
random_tensor = torch.rand(1,1,1,10)
print(random_tensor, random_tensor.shape)
# Remove single dimensions
removed_single_dimention = torch.rand(10)
print(removed_single_dimention, removed_single_dimention.shape)

# Print out tensors and their shapes


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.8549, 0.5509, 0.2868, 0.2063, 0.4451, 0.3593, 0.7204, 0.0731, 0.9699,
        0.1078]) torch.Size([10])
